name: Build

# on what events should github trigger the build workflow?
# in this case when code is pushed to any branch
on:
  push:
    branches: [ "**" ] # Note: `*`regex  matches all characters except '/'
                       #       `**` regex matches any branch on the repository


jobs:
  build-bookmarker-api:         # the job that we wish to execute
    name: Build bookmarker-api
    runs-on: ubuntu-latest      # you can pin the version as well like ubuntu-20.04
    defaults:
      run:
        working-directory: ./bookmarker-api # run the steps in this working directory
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'         # use java 17 version
          distribution: 'temurin'    # for aws you can set amazon-correto and azure -> microsoft distribution
          cache: maven
      - name: Build with Maven
        run: ./mvnw verify

      # conditional execution
      - if:  github.ref == 'refs/heads/master'  # execute this step only when the code is pushed on master branch
        name: Build and publish Docker Image
        run: |
          ./mvnw clean package jib:dockerBuild -DskipTests
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/bookmarker-api

    #
    # suggested by github:
    #
    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    #- name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
